plugins {
    id("readmore.android.baseline")
}

android {
    namespace "com.webtoonscorp.android.readmore.material.baseline"
    defaultConfig {
        applicationId "com.webtoonscorp.android.readmore.material.baseline"
    }
}

dependencies {
    implementation projects.readmoreMaterial
}

dependencyGuard {
    configuration("releaseRuntimeClasspath")
}

manifestShield {
    configuration("release")
}
