name: screenshot-comparison

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  screenshot-comparison:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact
      checks: read # for wait-on-check-action

    steps:
      - name: Checkout for getting base branch HEAD commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Get base branch HEAD commit for comparison
        id: get_base_branch_head
        run: echo "sha=$(git rev-parse origin/${{ github.base_ref }})" >> "$GITHUB_OUTPUT"

      - name: Checkout merged commit with base and pull-request branch
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Download screenshot artifact from base branch for comparison
        uses: dawidd6/action-download-artifact@v11
        continue-on-error: true
        with:
          name: test-reports
          workflow: unit-test.yml
          commit: ${{ steps.get_base_branch_head.outputs.sha }}
          if_no_artifact_found: fail

      - run: ./gradlew compareRoborazziDebug --stacktrace

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshot-diff-reports
          path: |
            **/reports
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
