name: Unit test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build tests & Create screenshots
        run: ./gradlew testDebugUnitTest --stacktrace

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            **/reports
            **/build/outputs/roborazzi
